version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my-redis-instance
    restart: always
    ports:
      - "0.0.0.0:6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass admin --appendonly yes
    networks:
      - java-pg
      
volumes:
  redis_data:
    driver: local
    
networks:
  java-pg:
    external: true
    name: myjava-pg